### ISSUE TITLE
iOSのホーム画面に追加するとキモくなる

### ISSUE THREAD

**Issue by mak0tia** [TinyKitten/tinykitten.github.io#5]
![Image](https://i.imgur.com/Mwh7LGO.jpg)
キモくない?

**Comment by mak0tia** [comment]
CodeHubから投稿したらクソみたいになってて草

**Comment by katabame** [comment]
`apple-touch-icon`を適切に設定すると解決できると思われます

**Comment by TinyKitten** [comment]
#6

**Comment by TinyKitten** [comment]
修正完了しました。ご報告ありがとうございます。
